package vista;

import java.awt.BorderLayout;
import java.util.TreeSet;
import logica.Producto;

public class DeTodoSA extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DeTodoSA.class.getName());

    public static TreeSet<Producto> productosSet = new TreeSet<>();

    /**
     * Creates new form DeTodoSA
     */
    public DeTodoSA() {
        initComponents();
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jdpPantallaDeInicio, BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPantallaDeInicio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiAdministrarProductos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsultarPorNombre = new javax.swing.JMenuItem();
        jmiConsultarPorPrecio = new javax.swing.JMenuItem();
        jmiConsultarPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpPantallaDeInicioLayout = new javax.swing.GroupLayout(jdpPantallaDeInicio);
        jdpPantallaDeInicio.setLayout(jdpPantallaDeInicioLayout);
        jdpPantallaDeInicioLayout.setHorizontalGroup(
            jdpPantallaDeInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        jdpPantallaDeInicioLayout.setVerticalGroup(
            jdpPantallaDeInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );

        jmAdministracion.setText("Administración");

        jmiAdministrarProductos.setText("Administrar productos");
        jmiAdministrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdministrarProductosActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiAdministrarProductos);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");
        jmConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultasActionPerformed(evt);
            }
        });

        jmiConsultarPorNombre.setText("Consultar por nombre");
        jmiConsultarPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarPorNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultarPorNombre);

        jmiConsultarPorPrecio.setText("Consultar por precio");
        jmiConsultarPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarPorPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultarPorPrecio);

        jmiConsultarPorRubro.setText("Consultar por rubro");
        jmiConsultarPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultarPorRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultarPorRubro);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPantallaDeInicio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpPantallaDeInicio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jmiAdministrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdministrarProductosActionPerformed
        jifAdministracionDeProductos administracion = new jifAdministracionDeProductos();
        jdpPantallaDeInicio.add(administracion);
        administracion.setVisible(true);

    }//GEN-LAST:event_jmiAdministrarProductosActionPerformed

    private void jmConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultasActionPerformed

    }//GEN-LAST:event_jmConsultasActionPerformed

    private void jmiConsultarPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarPorNombreActionPerformed
        jifConsultarPorNombre consultaNombre = new jifConsultarPorNombre();
        jdpPantallaDeInicio.add(consultaNombre);
        consultaNombre.setVisible(true);
    }//GEN-LAST:event_jmiConsultarPorNombreActionPerformed

    private void jmiConsultarPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarPorPrecioActionPerformed
        jifConsultarPorPrecio consultaPrecio = new jifConsultarPorPrecio();
        jdpPantallaDeInicio.add(consultaPrecio);
        consultaPrecio.setVisible(true);
    }//GEN-LAST:event_jmiConsultarPorPrecioActionPerformed

    private void jmiConsultarPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultarPorRubroActionPerformed
        jifConsultarPorRubro consultaRubro = new jifConsultarPorRubro();
        jdpPantallaDeInicio.add(consultaRubro);
        consultaRubro.setVisible(true);
    }//GEN-LAST:event_jmiConsultarPorRubroActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpPantallaDeInicio;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmiAdministrarProductos;
    private javax.swing.JMenuItem jmiConsultarPorNombre;
    private javax.swing.JMenuItem jmiConsultarPorPrecio;
    private javax.swing.JMenuItem jmiConsultarPorRubro;
    // End of variables declaration//GEN-END:variables
}
